// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/lzh-1625/go_process_manager/internal/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newProcess(db *gorm.DB, opts ...gen.DOOption) process {
	_process := process{}

	_process.processDo.UseDB(db, opts...)
	_process.processDo.UseModel(&model.Process{})

	tableName := _process.processDo.TableName()
	_process.ALL = field.NewAsterisk(tableName)
	_process.UUID = field.NewInt(tableName, "uuid")
	_process.Name = field.NewString(tableName, "name")
	_process.Cmd = field.NewString(tableName, "args")
	_process.Cwd = field.NewString(tableName, "cwd")
	_process.AutoRestart = field.NewBool(tableName, "auto_restart")
	_process.CompulsoryRestart = field.NewBool(tableName, "compulsory_restart")
	_process.PushIDs = field.NewString(tableName, "push_ids")
	_process.LogReport = field.NewBool(tableName, "log_report")
	_process.CgroupEnable = field.NewBool(tableName, "cgroup_enable")
	_process.MemoryLimit = field.NewFloat32(tableName, "memory_limit")
	_process.CpuLimit = field.NewFloat32(tableName, "cpu_limit")
	_process.Env = field.NewString(tableName, "env")

	_process.fillFieldMap()

	return _process
}

type process struct {
	processDo

	ALL               field.Asterisk
	UUID              field.Int
	Name              field.String
	Cmd               field.String
	Cwd               field.String
	AutoRestart       field.Bool
	CompulsoryRestart field.Bool
	PushIDs           field.String
	LogReport         field.Bool
	CgroupEnable      field.Bool
	MemoryLimit       field.Float32
	CpuLimit          field.Float32
	Env               field.String

	fieldMap map[string]field.Expr
}

func (p process) Table(newTableName string) *process {
	p.processDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p process) As(alias string) *process {
	p.processDo.DO = *(p.processDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *process) updateTableName(table string) *process {
	p.ALL = field.NewAsterisk(table)
	p.UUID = field.NewInt(table, "uuid")
	p.Name = field.NewString(table, "name")
	p.Cmd = field.NewString(table, "args")
	p.Cwd = field.NewString(table, "cwd")
	p.AutoRestart = field.NewBool(table, "auto_restart")
	p.CompulsoryRestart = field.NewBool(table, "compulsory_restart")
	p.PushIDs = field.NewString(table, "push_ids")
	p.LogReport = field.NewBool(table, "log_report")
	p.CgroupEnable = field.NewBool(table, "cgroup_enable")
	p.MemoryLimit = field.NewFloat32(table, "memory_limit")
	p.CpuLimit = field.NewFloat32(table, "cpu_limit")
	p.Env = field.NewString(table, "env")

	p.fillFieldMap()

	return p
}

func (p *process) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *process) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["uuid"] = p.UUID
	p.fieldMap["name"] = p.Name
	p.fieldMap["args"] = p.Cmd
	p.fieldMap["cwd"] = p.Cwd
	p.fieldMap["auto_restart"] = p.AutoRestart
	p.fieldMap["compulsory_restart"] = p.CompulsoryRestart
	p.fieldMap["push_ids"] = p.PushIDs
	p.fieldMap["log_report"] = p.LogReport
	p.fieldMap["cgroup_enable"] = p.CgroupEnable
	p.fieldMap["memory_limit"] = p.MemoryLimit
	p.fieldMap["cpu_limit"] = p.CpuLimit
	p.fieldMap["env"] = p.Env
}

func (p process) clone(db *gorm.DB) process {
	p.processDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p process) replaceDB(db *gorm.DB) process {
	p.processDo.ReplaceDB(db)
	return p
}

type processDo struct{ gen.DO }

type IProcessDo interface {
	gen.SubQuery
	Debug() IProcessDo
	WithContext(ctx context.Context) IProcessDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProcessDo
	WriteDB() IProcessDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProcessDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProcessDo
	Not(conds ...gen.Condition) IProcessDo
	Or(conds ...gen.Condition) IProcessDo
	Select(conds ...field.Expr) IProcessDo
	Where(conds ...gen.Condition) IProcessDo
	Order(conds ...field.Expr) IProcessDo
	Distinct(cols ...field.Expr) IProcessDo
	Omit(cols ...field.Expr) IProcessDo
	Join(table schema.Tabler, on ...field.Expr) IProcessDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProcessDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProcessDo
	Group(cols ...field.Expr) IProcessDo
	Having(conds ...gen.Condition) IProcessDo
	Limit(limit int) IProcessDo
	Offset(offset int) IProcessDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProcessDo
	Unscoped() IProcessDo
	Create(values ...*model.Process) error
	CreateInBatches(values []*model.Process, batchSize int) error
	Save(values ...*model.Process) error
	First() (*model.Process, error)
	Take() (*model.Process, error)
	Last() (*model.Process, error)
	Find() ([]*model.Process, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Process, err error)
	FindInBatches(result *[]*model.Process, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Process) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProcessDo
	Assign(attrs ...field.AssignExpr) IProcessDo
	Joins(fields ...field.RelationField) IProcessDo
	Preload(fields ...field.RelationField) IProcessDo
	FirstOrInit() (*model.Process, error)
	FirstOrCreate() (*model.Process, error)
	FindByPage(offset int, limit int) (result []*model.Process, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProcessDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p processDo) Debug() IProcessDo {
	return p.withDO(p.DO.Debug())
}

func (p processDo) WithContext(ctx context.Context) IProcessDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processDo) ReadDB() IProcessDo {
	return p.Clauses(dbresolver.Read)
}

func (p processDo) WriteDB() IProcessDo {
	return p.Clauses(dbresolver.Write)
}

func (p processDo) Session(config *gorm.Session) IProcessDo {
	return p.withDO(p.DO.Session(config))
}

func (p processDo) Clauses(conds ...clause.Expression) IProcessDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processDo) Returning(value interface{}, columns ...string) IProcessDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processDo) Not(conds ...gen.Condition) IProcessDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processDo) Or(conds ...gen.Condition) IProcessDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processDo) Select(conds ...field.Expr) IProcessDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processDo) Where(conds ...gen.Condition) IProcessDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processDo) Order(conds ...field.Expr) IProcessDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processDo) Distinct(cols ...field.Expr) IProcessDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processDo) Omit(cols ...field.Expr) IProcessDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processDo) Join(table schema.Tabler, on ...field.Expr) IProcessDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProcessDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processDo) RightJoin(table schema.Tabler, on ...field.Expr) IProcessDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processDo) Group(cols ...field.Expr) IProcessDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processDo) Having(conds ...gen.Condition) IProcessDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processDo) Limit(limit int) IProcessDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processDo) Offset(offset int) IProcessDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProcessDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processDo) Unscoped() IProcessDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processDo) Create(values ...*model.Process) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processDo) CreateInBatches(values []*model.Process, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processDo) Save(values ...*model.Process) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processDo) First() (*model.Process, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Process), nil
	}
}

func (p processDo) Take() (*model.Process, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Process), nil
	}
}

func (p processDo) Last() (*model.Process, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Process), nil
	}
}

func (p processDo) Find() ([]*model.Process, error) {
	result, err := p.DO.Find()
	return result.([]*model.Process), err
}

func (p processDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Process, err error) {
	buf := make([]*model.Process, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processDo) FindInBatches(result *[]*model.Process, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processDo) Attrs(attrs ...field.AssignExpr) IProcessDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processDo) Assign(attrs ...field.AssignExpr) IProcessDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processDo) Joins(fields ...field.RelationField) IProcessDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processDo) Preload(fields ...field.RelationField) IProcessDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processDo) FirstOrInit() (*model.Process, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Process), nil
	}
}

func (p processDo) FirstOrCreate() (*model.Process, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Process), nil
	}
}

func (p processDo) FindByPage(offset int, limit int) (result []*model.Process, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processDo) Delete(models ...*model.Process) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processDo) withDO(do gen.Dao) *processDo {
	p.DO = *do.(*gen.DO)
	return p
}
