// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/lzh-1625/go_process_manager/internal/app/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWsShare(db *gorm.DB, opts ...gen.DOOption) wsShare {
	_wsShare := wsShare{}

	_wsShare.wsShareDo.UseDB(db, opts...)
	_wsShare.wsShareDo.UseModel(&model.WsShare{})

	tableName := _wsShare.wsShareDo.TableName()
	_wsShare.ALL = field.NewAsterisk(tableName)
	_wsShare.ID = field.NewUint(tableName, "id")
	_wsShare.CreatedAt = field.NewTime(tableName, "created_at")
	_wsShare.UpdatedAt = field.NewTime(tableName, "updated_at")
	_wsShare.DeletedAt = field.NewField(tableName, "deleted_at")
	_wsShare.Pid = field.NewInt(tableName, "pid")
	_wsShare.Write = field.NewBool(tableName, "write")
	_wsShare.ExpireTime = field.NewTime(tableName, "expire_time")
	_wsShare.CreateBy = field.NewString(tableName, "create_by")
	_wsShare.Token = field.NewString(tableName, "token")

	_wsShare.fillFieldMap()

	return _wsShare
}

type wsShare struct {
	wsShareDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	Pid        field.Int
	Write      field.Bool
	ExpireTime field.Time
	CreateBy   field.String
	Token      field.String

	fieldMap map[string]field.Expr
}

func (w wsShare) Table(newTableName string) *wsShare {
	w.wsShareDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wsShare) As(alias string) *wsShare {
	w.wsShareDo.DO = *(w.wsShareDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wsShare) updateTableName(table string) *wsShare {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewUint(table, "id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")
	w.Pid = field.NewInt(table, "pid")
	w.Write = field.NewBool(table, "write")
	w.ExpireTime = field.NewTime(table, "expire_time")
	w.CreateBy = field.NewString(table, "create_by")
	w.Token = field.NewString(table, "token")

	w.fillFieldMap()

	return w
}

func (w *wsShare) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wsShare) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 9)
	w.fieldMap["id"] = w.ID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt
	w.fieldMap["pid"] = w.Pid
	w.fieldMap["write"] = w.Write
	w.fieldMap["expire_time"] = w.ExpireTime
	w.fieldMap["create_by"] = w.CreateBy
	w.fieldMap["token"] = w.Token
}

func (w wsShare) clone(db *gorm.DB) wsShare {
	w.wsShareDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wsShare) replaceDB(db *gorm.DB) wsShare {
	w.wsShareDo.ReplaceDB(db)
	return w
}

type wsShareDo struct{ gen.DO }

type IWsShareDo interface {
	gen.SubQuery
	Debug() IWsShareDo
	WithContext(ctx context.Context) IWsShareDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWsShareDo
	WriteDB() IWsShareDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWsShareDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWsShareDo
	Not(conds ...gen.Condition) IWsShareDo
	Or(conds ...gen.Condition) IWsShareDo
	Select(conds ...field.Expr) IWsShareDo
	Where(conds ...gen.Condition) IWsShareDo
	Order(conds ...field.Expr) IWsShareDo
	Distinct(cols ...field.Expr) IWsShareDo
	Omit(cols ...field.Expr) IWsShareDo
	Join(table schema.Tabler, on ...field.Expr) IWsShareDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWsShareDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWsShareDo
	Group(cols ...field.Expr) IWsShareDo
	Having(conds ...gen.Condition) IWsShareDo
	Limit(limit int) IWsShareDo
	Offset(offset int) IWsShareDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWsShareDo
	Unscoped() IWsShareDo
	Create(values ...*model.WsShare) error
	CreateInBatches(values []*model.WsShare, batchSize int) error
	Save(values ...*model.WsShare) error
	First() (*model.WsShare, error)
	Take() (*model.WsShare, error)
	Last() (*model.WsShare, error)
	Find() ([]*model.WsShare, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WsShare, err error)
	FindInBatches(result *[]*model.WsShare, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WsShare) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWsShareDo
	Assign(attrs ...field.AssignExpr) IWsShareDo
	Joins(fields ...field.RelationField) IWsShareDo
	Preload(fields ...field.RelationField) IWsShareDo
	FirstOrInit() (*model.WsShare, error)
	FirstOrCreate() (*model.WsShare, error)
	FindByPage(offset int, limit int) (result []*model.WsShare, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWsShareDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wsShareDo) Debug() IWsShareDo {
	return w.withDO(w.DO.Debug())
}

func (w wsShareDo) WithContext(ctx context.Context) IWsShareDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wsShareDo) ReadDB() IWsShareDo {
	return w.Clauses(dbresolver.Read)
}

func (w wsShareDo) WriteDB() IWsShareDo {
	return w.Clauses(dbresolver.Write)
}

func (w wsShareDo) Session(config *gorm.Session) IWsShareDo {
	return w.withDO(w.DO.Session(config))
}

func (w wsShareDo) Clauses(conds ...clause.Expression) IWsShareDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wsShareDo) Returning(value interface{}, columns ...string) IWsShareDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wsShareDo) Not(conds ...gen.Condition) IWsShareDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wsShareDo) Or(conds ...gen.Condition) IWsShareDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wsShareDo) Select(conds ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wsShareDo) Where(conds ...gen.Condition) IWsShareDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wsShareDo) Order(conds ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wsShareDo) Distinct(cols ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wsShareDo) Omit(cols ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wsShareDo) Join(table schema.Tabler, on ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wsShareDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wsShareDo) RightJoin(table schema.Tabler, on ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wsShareDo) Group(cols ...field.Expr) IWsShareDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wsShareDo) Having(conds ...gen.Condition) IWsShareDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wsShareDo) Limit(limit int) IWsShareDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wsShareDo) Offset(offset int) IWsShareDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wsShareDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWsShareDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wsShareDo) Unscoped() IWsShareDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wsShareDo) Create(values ...*model.WsShare) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wsShareDo) CreateInBatches(values []*model.WsShare, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wsShareDo) Save(values ...*model.WsShare) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wsShareDo) First() (*model.WsShare, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WsShare), nil
	}
}

func (w wsShareDo) Take() (*model.WsShare, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WsShare), nil
	}
}

func (w wsShareDo) Last() (*model.WsShare, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WsShare), nil
	}
}

func (w wsShareDo) Find() ([]*model.WsShare, error) {
	result, err := w.DO.Find()
	return result.([]*model.WsShare), err
}

func (w wsShareDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WsShare, err error) {
	buf := make([]*model.WsShare, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wsShareDo) FindInBatches(result *[]*model.WsShare, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wsShareDo) Attrs(attrs ...field.AssignExpr) IWsShareDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wsShareDo) Assign(attrs ...field.AssignExpr) IWsShareDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wsShareDo) Joins(fields ...field.RelationField) IWsShareDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wsShareDo) Preload(fields ...field.RelationField) IWsShareDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wsShareDo) FirstOrInit() (*model.WsShare, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WsShare), nil
	}
}

func (w wsShareDo) FirstOrCreate() (*model.WsShare, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WsShare), nil
	}
}

func (w wsShareDo) FindByPage(offset int, limit int) (result []*model.WsShare, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wsShareDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wsShareDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wsShareDo) Delete(models ...*model.WsShare) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wsShareDo) withDO(do gen.Dao) *wsShareDo {
	w.DO = *do.(*gen.DO)
	return w
}
